services:
  # 1. FRONTEND (React + Vite + Nginx)
  frontend:
    container_name: exploree_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    stdin_open: true
    tty: true
    ports:
      - "8100:5173"           # JAVÍTVA: A Vite belső portja 5173, ezt vezetjük ki a 8100-ra
    restart: unless-stopped

  # 2. ADATBÁZIS (MySQL)
  db:
    image: mysql:8.4
    container_name: exploree_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: exploree
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppw
    ports:
      - "3307:3306"
    volumes:
      - exploree_db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d:ro 
    healthcheck:              # JAVÍTVA: Ez kell ahhoz, hogy a phpmyadmin bevárja a MySQL-t
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-prootpw"]
      timeout: 20s
      retries: 10

  # 3. PHPMYADMIN (Adatbázis kezelő)
  phpmyadmin:
    image: phpmyadmin
    container_name: exploree_phpmyadmin
    restart: always
    ports:
      - "8101:80"   
    environment:
      PMA_HOST: db            # JAVÍTVA: mysqldb helyett db
      PMA_USER: root
      PMA_PASSWORD: "rootpw"  # JAVÍTVA: Üres helyett a MySQL root jelszava
      PMA_ARBITRARY: 1
    depends_on:
      db:                     # JAVÍTVA: mysqldb helyett db
        condition: service_healthy

  # 4. BACKEND API (Node.js)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exploree_api
    depends_on:
      - db                    # JAVÍTVA: mysqldb helyett db
    environment:
      DB_HOST: db             # JAVÍTVA: mysqldb helyett db
      DB_USER: root
      DB_PASSWORD: "rootpw"   # JAVÍTVA: Üres helyett a MySQL root jelszava
      DB_DATABASE: exploree
      PORT: 5050
    ports:
      - "5050:5050"           # Backend elérése: http://localhost:5050

volumes:
  exploree_db_data: